Dwlad90/stylex-swc-plugin

.changeset/mighty-years-mate.md
packages/swc-plugin/src/transform/fold/fold_export_default_expr.rs
packages/swc-plugin/tests/__swc_snapshots__/tests/stylex_transform_call_test/keep_stylex_create_when_needed_test/even_when_stylex_calls_come_first.rs/stylex_call_with_mixed_access_export_default.js
packages/swc-plugin/tests/__swc_snapshots__/tests/stylex_transform_call_test/keep_stylex_create_when_needed_test/even_when_stylex_calls_come_first.rs/stylex_call_with_mixed_access_inline_export_default.js
packages/swc-plugin/tests/__swc_snapshots__/tests/stylex_transform_call_test/keep_stylex_create_when_needed_test/even_when_stylex_calls_come_first.rs/stylex_call_with_mixed_access_inline_named_export.js
packages/swc-plugin/tests/__swc_snapshots__/tests/stylex_transform_call_test/keep_stylex_create_when_needed_test/even_when_stylex_calls_come_first.rs/stylex_call_with_mixed_access_named_export.js
packages/swc-plugin/tests/__swc_snapshots__/tests/stylex_transform_call_test/keep_stylex_create_when_needed_test/keep_stylex_create_when_needed.rs/stylex_call_with_export_default.js
packages/swc-plugin/tests/__swc_snapshots__/tests/stylex_transform_call_test/keep_stylex_create_when_needed_test/keep_stylex_create_when_needed.rs/stylex_call_with_inline_export_default.js
packages/swc-plugin/tests/__swc_snapshots__/tests/stylex_transform_call_test/keep_stylex_create_when_needed_test/keep_stylex_create_when_needed.rs/stylex_call_with_inline_named_export.js
packages/swc-plugin/tests/__swc_snapshots__/tests/stylex_transform_call_test/keep_stylex_create_when_needed_test/keep_stylex_create_when_needed.rs/stylex_call_with_named_export.js
packages/swc-plugin/tests/stylex_transform_call_test/keep_stylex_create_when_needed_test/even_when_stylex_calls_come_first.rs
packages/swc-plugin/tests/stylex_transform_call_test/keep_stylex_create_when_needed_test/keep_stylex_create_when_needed.rs

fixing #10
This PR added reference counting to default exports and fixed a bug with deleting exported by default module item

feat(reference counting): count export default reference

---

Cargo.lock
crates/stylex-shared/src/shared/enums/data_structures/evaluate_result_value.rs
crates/stylex-shared/src/shared/utils/core/stylex_merge.rs
crates/stylex-shared/src/shared/utils/js/evaluate.rs
crates/stylex-shared/tests/__swc_snapshots__/tests/stylex_validation_create_test/stylex_validation_create_dynamic_test.rs/dynamic_style_function_only_accepts_named_parameters_valid_with_other_styles.js
crates/stylex-shared/tests/fixture/counter-with-dynamic-styles/input.js
crates/stylex-shared/tests/fixture/counter-with-dynamic-styles/rs_output.js
crates/stylex-shared/tests/fixture/counter-with-dynamic-styles/rs_output_prod.js
crates/stylex-shared/tests/fixture/counter-with-dynamic-styles/wasm_output.js
crates/stylex-shared/tests/fixture/counter-with-dynamic-styles/wasm_output_prod.js
crates/stylex-shared/tests/stylex_validation_create_test/stylex_validation_create_dynamic_test.rs
packages/nextjs-plugin/package.json
packages/nextjs-swc-plugin/package.json

This PR adds correct transformation of dynamic styles in the `stylex.props` call
See issue #49 for more details

feat(stylex.props): transform dynamic styles

---

crates/stylex-rs-compiler/README.md
crates/stylex-swc-plugin/README.md

This PR update `@stylexswc/swc-plugin` documentation
See issue https://github.com/Dwlad90/stylex-swc-plugin/issues/62 for more details

docs(@stylexswc/swc-plugin): add using examples with some bundlers

---

Cargo.lock
crates/stylex-path-resolver/fixtures/exports/node_modules/stylex-lib-dist-exports-with-main/package.json
crates/stylex-path-resolver/fixtures/exports/package.json
crates/stylex-path-resolver/fixtures/workspace/node_modules/@stylex/theme-lib-main-dist/package.json
crates/stylex-path-resolver/fixtures/workspace/package.json
crates/stylex-path-resolver/src/package_json/mod.rs
crates/stylex-path-resolver/src/resolvers/mod.rs
crates/stylex-path-resolver/src/resolvers/tests.rs

fix(@stylexswc/path-resolver): fix finding nearest packages.json

---

.github/SECURITY.md

docs: add security.md

---

crates/stylex-shared/src/shared/constants/common.rs
crates/stylex-shared/src/shared/utils/css/common.rs
crates/stylex-shared/src/shared/utils/css/normalizers/tests/base.rs
crates/stylex-shared/src/shared/utils/css/tests/css_custom_properties_validation_test.rs

fix(css functions): exclude oklch and oklab functions from normalizing

---

crates/stylex-shared/src/shared/constants/common.rs
crates/stylex-shared/src/shared/regex.rs
crates/stylex-shared/src/shared/utils/css/common.rs
crates/stylex-shared/src/shared/utils/css/normalizers/tests/base.rs
crates/stylex-shared/src/shared/utils/css/normalizers/whitespace_normalizer.rs
crates/stylex-shared/src/shared/utils/css/tests/css_custom_properties_validation_test.rs

Split CSS normalization test to male smaller tests

refactor: split css normalization test to many smaller tests

---

crates/stylex-shared/tests/__swc_snapshots__/tests/stylex_transform_misc/react.rs/stylex_call_using_styles_inside_use_memo.js
crates/stylex-shared/tests/fold.rs
crates/stylex-shared/tests/stylex_transform_misc/mod.rs
crates/stylex-shared/tests/stylex_transform_misc/react.rs

test(stylex_transform_misc): add test to using props into useMemo

---

crates/stylex-swc-plugin/README.md
crates/stylex-swc-plugin/package.json

chore(@stylexswc/swc-plugin): marked as deprecated

---

apps/rspack-unplugin-example/package.json
package.json
packages/webpack-plugin/src/stylex-loader.ts
pnpm-lock.yaml

This PR upgrade dependencies that have vulnerabilities

chore(deps): override dependencies with vulnerable versions

---

crates/stylex-rs-compiler/.gitignore
crates/stylex-rs-compiler/benchmark/bench.ts

Update `@stylexswc/rs-compiler` benchmark

chore(@stylexswc/rs-compiler): add rollup example app styles to benchmark

---

README.md

docs(readme): mark @stylexswc/swc-plugin as finally deprecated

---

Cargo.lock
Cargo.toml
crates/stylex-shared/Cargo.toml
crates/stylex-shared/src/shared/regex.rs
crates/stylex-shared/src/shared/transformers/stylex_keyframes.rs
crates/stylex-shared/src/shared/transformers/tests/stylex_create_test.rs
crates/stylex-shared/src/shared/utils/common.rs
crates/stylex-shared/src/shared/utils/core/convert_style_to_class_name.rs
crates/stylex-shared/src/shared/utils/css/normalizers/base.rs
crates/stylex-shared/tests/__swc_snapshots__/tests/stylex_transform_create_test/stylex_create_call.rs/transforms_style_object_with_webkit_property_as_value.js
crates/stylex-shared/tests/stylex_transform_create_test/stylex_create_call.rs
packages/nextjs-plugin/package.json

This PR fix transforming  `-webkit-prefixed` properties 

Fix webkit properties

---

.github/workflows/cleanup.yaml
README.md

ci(ga): add cache cleanup

---

.github/workflows/conventional-label.yaml

Add automatically conventional release labels to PRs

ci(ga): add conventional release labels

---

.github/actions/gitconfig/action.yml
.github/workflows/conventional-label.yaml
.github/workflows/release.yml
scripts/functions.sh

ci(release): add checkout step to publish

---

.github/workflows/release.yml

ci(ga release): check upload status every 30 seconds

---

.github/workflows/cleanup.yaml
.github/workflows/npm.yml

ci(ga): cleanup caches after uploading to npm

---

.github/workflows/cleanup.yaml
.github/workflows/npm.yml

ci(ga): fix cleaning benchmark caches

---

.github/release.yml

ci(changelog): update ci labels

---

.github/workflows/npm.yml
.github/workflows/release.yml

fix(npm): add checkout to cleanup job

---

.github/actions/gitconfig/action.yml
.github/workflows/release.yml

ci(ga): fix committer name and email

---

.github/workflows/cleanup.yaml

ci(ga): cleanup caches on deleting branches

---

.github/workflows/cleanup.yaml

ci(ga): fix pr cleanup event name

---

.github/workflows/fast-forward.yml

ci(ga): fast forward PR merge

---

.github/workflows/cleanup.yaml
.github/workflows/fast-forward.yml

ci(ga cleanup): continue when cache not found

---

.github/workflows/cleanup.yaml
.github/workflows/npm.yml

ci(ga): fire cleanup on closing PR

---

.github/workflows/conventional-label.yaml
.github/workflows/npm.yml
.github/workflows/pr-validation.yml
.github/workflows/self-approve.yml

This reverts commit e00721d6dc1042fdfea70d81651bd85ca7bdfaeb.

Reapply: ci(ga) set benchmark artifacts cross PRs

---

.github/workflows/cleanup-branch.yaml
.github/workflows/cleanup-pr.yaml
.github/workflows/cleanup.yaml
.github/workflows/npm.yml

ci(workflows): add cleanup workflow

---

.github/workflows/release.yml

ci(release): check fast-forward only against master

---

crates/stylex-path-resolver/src/resolvers/mod.rs

Relative import path should contain extension
This PR solves an issue with resolving relative import paths

fix(@stylexswc/path-resolver): normalize relative import path

---

.github/workflows/npm.yml
.github/workflows/release.yml

ci(release): add retries to checking NPM workflow status

---

.github/workflows/cleanup-branch.yaml
.github/workflows/cleanup-pr.yaml
.github/workflows/fast-forward.yml
.github/workflows/npm.yml
.github/workflows/pr-validation.yml
.github/workflows/release.yml

ci(ga): clean caches after PR merged

---

apps/nextjs-postcss-example/next.config.js
apps/nextjs-postcss-example/postcss.config.js
packages/postcss-plugin/src/bundler.ts
packages/postcss-plugin/src/index.ts

This PR fix class mismatching on dev build of `@stylexswc/next-postcss-example`
(Optional) Fixes #196 

fix(@stylexswc/next-postcss-example): pass correct rsOptions

---

apps/esbuild-unplugin-example/package.json
apps/farm-unplugin-example/package.json
apps/nextjs-example/package.json
apps/nextjs-postcss-example/package.json
apps/nextjs-swc-example/package.json
apps/rollup-example/package.json
apps/rollup-unplugin-example/package.json
apps/rsbuild-unplugin-example/package.json
apps/rspack-unplugin-example/package.json
apps/solid-unplugin-example/package.json
apps/vite-unplugin-example/package.json
apps/vue-unplugin-example/package.json
apps/webpack-example/package.json
apps/webpack-unplugin-example/package.json
crates/stylex-path-resolver/fixtures/workspace/package.json
crates/stylex-rs-compiler/package.json
packages/nextjs-swc-plugin/package.json
packages/postcss-plugin/package.json
packages/rollup-plugin/package.json
packages/unplugin/package.json
packages/webpack-plugin/package.json
pnpm-lock.yaml

chore(deps): upgrade @stylexjs/stylex to 0.10.0

---

.github/workflows/npm.yml
.github/workflows/pr-validation.yml

ci(npm): copy @stylexswc/rs-compiler artifacts

---

.github/PULL_REQUEST_TEMPLATE.md
crates/stylex-path-resolver/package.json
crates/stylex-rs-compiler/package.json
crates/stylex-swc-plugin/package.json
crates/stylex-test-parser/package.json
packages/jest/package.json
packages/nextjs-plugin/package.json
packages/nextjs-swc-plugin/package.json
packages/postcss-plugin/package.json
packages/rollup-plugin/package.json
packages/unplugin/package.json
packages/webpack-plugin/package.json
scripts/packages/build/rust.sh

This pull request includes several updates across multiple `package.json` files and a script file to improve the build process and artifact checking. The most significant changes involve adding post-build checks and improving the Rust build script.
(Optional) Issue #205

chore: add `postbuild` script to all buildable public packages

---

crates/stylex-rs-compiler/package.json

fix: disable checking artifacts because of bun on Windows

---

crates/stylex-path-resolver/src/resolvers/mod.rs
crates/stylex-path-resolver/src/resolvers/tests.rs

This PR includes changes to the `stylex-path-resolver` crate to improve the file path resolution logic and update the related tests

fix(stylex_compiler_rs): improve resolving StyleX calls from dependencies

---

.github/workflows/cleanup-branch.yaml
.github/workflows/cleanup-pr.yaml
.github/workflows/cleanup.yaml
.github/workflows/fast-forward.yml
.github/workflows/npm.yml

ci(ga): fix excluding turbo cache

---

.github/release.yml
.github/workflows/conventional-label.yaml
packages/jest/package.json
packages/nextjs-plugin/package.json
packages/postcss-plugin/package.json
packages/rollup-plugin/package.json
packages/webpack-plugin/package.json
pnpm-lock.yaml

This P includes updates to the `package.json` files of several packages and modifications to the `pnpm-lock.yaml` file to adjust dependencies and their versions. The changes ensure that the `@stylexswc/rs-compiler` dependency is consistently included in the `dependencies` section across various packages and clean up redundant version references in the lock file.

chore(deps): move @stylexswc/rs-compiler to dependencies

---

.github/workflows/release.yml
crates/stylex-rs-compiler/package.json
package.json
patches/scripty@2.1.1.patch
pnpm-lock.yaml

Link to PR with this commit:
https://github.com/testdouble/scripty/pull/100

chore: patch `script` package to use `cross-spawn`

---

crates/stylex-path-resolver/src/file_system/mod.rs
crates/stylex-path-resolver/src/package_json/mod.rs
crates/stylex-path-resolver/src/resolvers/mod.rs
crates/stylex-path-resolver/src/resolvers/tests.rs
crates/stylex-rs-compiler/package.json
crates/stylex-shared/package.json
crates/stylex-shared/src/shared/structures/state_manager.rs
pnpm-lock.yaml

This PR fix export field resolution with multiple nested node_modules in a workspace
(Optional) Issu #223 

fix(stylex_path_resolver): export field resolution with multiple node_modules in a workspace

---

.github/workflows/npm.yml
.github/workflows/pr-validation.yml

This PR includes updates to the caching keys used in the GitHub Actions workflows for both `npm.yml` and `pr-validation.yml` files. These changes aim to improve the efficiency and reliability of cache restoration during continuous integration runs.

ci: normalize benchmark cache keys

---

package.json
pnpm-lock.yaml

This pull request includes updates to the `package.json` file to add new dependencies and update existing ones.
Dependency updates:
* Added `koa` with version constraint `>=2.0.0` and version `^2.15.4`.
* Added `esbuild` with version constraint `<=0.24.2` and version `^0.25.0`.

chore: override dependencies with vulnerabilities

---

.czrc
README.md
commitlint.config.js
packages/design-system/README.md

This pull request includes several changes to configuration files and documentation to improve commit message standards and clarify internal usage of the design system.

chore(commitlint): update config

---

.github/workflows/pr-validation.yml

This pull request includes a change to the `.github/workflows/pr-validation.yml` file to enhance the commit message validation process.

Add commit lintio

---

.github/dependabot.yml
.github/workflows/conventional-label.yaml

This pull request includes updates to the Dependabot configuration and workflow files to improve dependency management and labeling.

ci(dependabot): monthly update of npm packages and cargo crates

---

crates/stylex-shared/src/shared/structures/state_manager.rs
crates/stylex-shared/src/shared/utils/common.rs
crates/stylex-shared/src/shared/utils/js/evaluate.rs
crates/stylex-shared/src/shared/utils/log/build_code_frame_error.rs
crates/stylex-shared/src/shared/utils/mod.rs
crates/stylex-shared/src/shared/utils/vector.rs
crates/stylex-shared/src/transform/fold.rs
crates/stylex-shared/src/transform/fold/fold_fn_declarator.rs
crates/stylex-shared/src/transform/fold/fold_import_decl.rs
crates/stylex-shared/src/transform/fold/fold_module_items.rs
crates/stylex-shared/src/transform/fold/fold_var_declarator.rs
crates/stylex-shared/tests/__swc_snapshots__/tests/stylex_transform_misc/react.rs/stylex_call_with_redaclare_function_from_other_scope_in_dev_mode.js
crates/stylex-shared/tests/__swc_snapshots__/tests/stylex_transform_misc/react.rs/stylex_call_with_redaclare_function_from_other_scope_in_prod_mode.js
crates/stylex-shared/tests/__swc_snapshots__/tests/stylex_transform_misc/react.rs/stylex_call_with_redaclare_variable_from_other_scope_in_prod_mode.js
crates/stylex-shared/tests/evaluation/args_module_transform.rs
crates/stylex-shared/tests/evaluation/evaluation_module_transform.rs
crates/stylex-shared/tests/evaluation/stylex_evaluation/stylex_evaluation_common.rs
crates/stylex-shared/tests/fixture/spot-loader/output.js
crates/stylex-shared/tests/fixture/typography/output.js
crates/stylex-shared/tests/stylex_transform_misc/react.rs

This pull request introduces several changes to the `stylex-shared` crate, focusing on improving the management of state and declarations, enhancing error handling, and adding utility functions. The most important changes include adding new fields to the `StateManager` struct, refactoring the handling of declarations, and improving error reporting.
(Optional) Issue # 258

feat(stylex_shared): improve variable declaration validating

---

crates/stylex-rs-compiler/src/lib.rs
crates/stylex-shared/src/shared/structures/state_manager.rs
crates/stylex-shared/src/shared/utils/core/add_source_map_data.rs
crates/stylex-shared/src/shared/utils/log/build_code_frame_error.rs
crates/stylex-shared/src/shared/utils/validators.rs
crates/stylex-shared/src/transform/stylex/transform_stylex_create_call.rs
crates/stylex-shared/src/transform/stylex/transform_stylex_create_theme_call.rs
crates/stylex-shared/src/transform/stylex/transform_stylex_define_vars_call.rs
crates/stylex-shared/src/transform/stylex/transform_stylex_keyframes_call.rs

This pull request includes several changes to improve error handling, logging, and state management in the `stylex` crate. The most important changes include adding detailed error messages, introducing logging for debugging purposes, and modifying function signatures to use mutable references to `StateManager`.

fix(add_source_map_data): handle error on finding source code fragment

---

crates/stylex-rs-compiler/benchmark/bench.ts

This pull request to `crates/stylex-rs-compiler/benchmark/bench.ts` includes changes to enhance the benchmarking process by adding a new benchmark for handling a large number of styles. The most important changes include the creation of a new benchmark instance, updating the benchmark tasks, and modifying the output handling to accommodate the new benchmark.
Enhancements to benchmarking process:
* Created a new benchmark instance `benchLotsOfStyles` with additional configuration options such as `time`, `iterations`, `warmupIterations`, and `warmupTime`.
* Updated the existing benchmark task to use `benchRegular` instead of the previous instance `b`.
* Added new tasks to the `benchLotsOfStyles` benchmark for specific files in the `rollupPluginAppFiles` array.
* Modified the execution and …

test(benchmark): reduce number of running  samples for large style sets

---

.github/workflows/sync-deps.yml

This pull request introduces a new GitHub Actions workflow to automatically synchronize peer dependencies in the project whenever a pull request modifies any `package.json` file. The most important changes include the creation of a new workflow file and the configuration of various steps to ensure dependencies are consistent.
New GitHub Actions workflow:
* [`.github/workflows/sync-deps.yml`](diffhunk://#diff-c8b8d68de97b62020c4de3773113503751649bd9f8d681fedfe30d4af398a2e1R1-R50): Added a workflow named "Sync Dependencies" that triggers on pull requests affecting `package.json` files. It includes steps to check out the code, set up `pnpm`, list and fix dependency mismatches, and commit and push any changes. Additionally, it comments on the pull request to inform about the synchronization.

ci(dependabot): add workflow to sync dependencies

---

.syncpackrc
apps/nextjs-example/package.json
apps/nextjs-postcss-example/package.json
packages/nextjs-plugin/package.json
packages/unplugin/package.json
pnpm-lock.yaml

This pull request includes multiple changes to update the version specifications for dependencies across various files. The primary focus is on changing fixed version numbers to use range specifiers, which allows for greater flexibility in dependency management.
Dependency version updates:
* [`.syncpackrc`](diffhunk://#diff-aac9fa94496fd53bd351b6dbf9fa82cfd55e6abcff3b0f27169590744b2c5747L5): Removed the `peer` dependency type.
* [`apps/nextjs-example/package.json`](diffhunk://#diff-42d95041844ffeb8391778ecd69c79be29736a1b1d3adcb9333c15bdebd6a370L27-R27): Updated `next` dependency to use `^15.2.3` instead of `15.2.3`.
* [`apps/nextjs-postcss-example/package.json`](diffhunk://#diff-6e638040715ebb1752b492845fdd6805bbe5c2b7b217e21e2f32ab7102622503L28-R28): Updated `next` dependency to use …

deps(stylexswc/nextjs-plugin): set minimal peer next version to 15.0.0

---

.czrc
.github/workflows/pr-validation.yml
Cargo.lock
Cargo.toml

This pull request introduces changes to dependency management, CI workflow behavior, and Rust project dependencies. The most notable updates include adding a new commit type for development dependencies, improving the pull request validation workflow to handle fast-forward merge failures, and upgrading several Rust dependencies.
* [`.czrc`](diffhunk://#diff-9a4f4c5d4e611c2a9c60292f63f6356d0e6a580ae69079b3b6a62a7e03efdb7fR26-R29): Added a new commit type, `dev-deps`, for development dependencies with a description and title.
* [`.github/workflows/pr-validation.yml`](diffhunk://#diff-04af3c9c96028eebf4fa93d5c67e1fa08255fb7a3682f912ccd5bea1dff5ccd4L205-R209): Updated the pull request validation workflow to handle fast-forward merge failures gracefully by posting a comment requesting a rebase …

deps(cargo): update common crates to latest versions

---

package.json
pnpm-lock.yaml

This pull request focuses on dependency updates and cleanup in `package.json` and `pnpm-lock.yaml`. The most significant changes involve updating the versions of `brace-expansion` and `balanced-match`, introducing the `concat-map` package, and ensuring consistency in dependency snapshots.
* Updated `brace-expansion` versions in `package.json` and `pnpm-lock.yaml` to `1.1.12` and `2.0.2` for compatibility and improved stability. [[1]](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L66-R67) [[2]](diffhunk://#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL23-R24) [[3]](diffhunk://#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL4156-R4159)
* Downgraded `balanced-match` from version `3.0.1` to `1.0.2` to align with …

fix(stylexoptions): serialize styleResolution option to StyleResolution enum v2

---

package.json
pnpm-lock.yaml

This pull request updates dependencies in the `package.json` and `pnpm-lock.yaml` files to ensure compatibility and incorporate the latest patches. The most significant changes involve upgrading versions of `form-data` and `@eslint/plugin-kit`, as well as adding new dependencies for `@eslint/core`.
* **`form-data`**:
- Upgraded from version `4.0.1` to `4.0.4` in `pnpm-lock.yaml` to include bug fixes and enhancements. [[1]](diffhunk://#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL5625-R5632) [[2]](diffhunk://#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL14370-R14385) [[3]](diffhunk://#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL15678-R15690)
* **`@eslint/plugin-kit`**:
- Upgraded from version `0.3.1` to `0.3.4` in …

chore(deps): update pnpm overrides and patched dependencies for security and compatibility

---

Makefile
README.md

This pull request updates the `README.md` file to include detailed documentation for a new Makefile-based development workflow. The changes provide a comprehensive guide to setting up, building, testing, and managing the project using the Makefile, with categorized commands for different aspects of development.
* Added a "Development" section to the `README.md` that introduces the Makefile and its integration with Node.js and Rust ecosystems. It includes a "Quick Start" guide with examples of common commands (`make setup`, `make build`, `make test`, etc.).
* Listed all available Makefile commands, organized into categories such as Setup, Build, Development, Quality, Test, App, Documentation & Release, Package Commands, and Rust Crate Operations. Each category includes detailed …

chore: add makefile
