Dwlad90/stylex-swc-plugin

.changeset/fast-moles-flow.md, packages/swc-plugin/src/shared/enums/core.rs, packages/swc-plugin/src/transform/fold/fold_export_decl.rs, packages/swc-plugin/src/transform/fold/fold_expr.rs, packages/swc-plugin/src/transform/fold/fold_ident.rs, packages/swc-plugin/src/transform/fold/fold_import_decl.rs, packages/swc-plugin/src/transform/fold/fold_member_expression.rs, packages/swc-plugin/src/transform/fold/fold_module.rs, packages/swc-plugin/src/transform/fold/fold_module_items.rs, packages/swc-plugin/src/transform/fold/fold_var_declarator.rs
To speed up file processing, a new folding cycle has been added that allows processing only application files, skipping files that do not have StyleX package imports
=> feat(folding): add new cycle to prevent filing state for non application's files

.changeset/perfect-days-talk.md, packages/swc-plugin/Cargo.lock, packages/swc-plugin/Cargo.toml, packages/swc-plugin/src/shared/regex.rs, packages/swc-plugin/src/shared/transformers/stylex_include.rs, packages/swc-plugin/src/shared/utils/ast/convertors.rs, packages/swc-plugin/src/shared/utils/ast/factories.rs, packages/swc-plugin/src/shared/utils/ast/mod.rs, packages/swc-plugin/src/shared/utils/ast/tests/convertors_tests.rs, packages/swc-plugin/src/shared/utils/ast/tests/mod.rs, packages/swc-plugin/src/shared/utils/core/evaluate_stylex_create_arg.rs, packages/swc-plugin/src/shared/utils/core/flatten_raw_style_object.rs, packages/swc-plugin/src/shared/utils/core/make_string_expression.rs, packages/swc-plugin/src/shared/utils/core/tests/stylex_tests.rs, packages/swc-plugin/src/shared/utils/js/evaluate.rs, packages/swc-plugin/tests/__swc_snapshots__/tests/stylex_transform_define_vars_test/stylex_transform_define_vars.rs/transforms_variables_object_with_key_containing_differend_symbols.js, packages/swc-plugin/tests/evaluation/stylex_evaluation/stylex_evaluation_common.rs, packages/swc-plugin/tests/stylex_transform_create_test/stylex_create_call.rs, packages/swc-plugin/tests/stylex_transform_define_vars_test/stylex_transform_define_vars.rs
This PR improves the validation of object keys, it was correctly noted in the PR #12, thank you to @budde377.
`Ident::verify_symbol` is used in pair with `ctx.is_reserved_word`  because reserved words do not need to be wrapped in quotes, as is done in StyleX babel plugin.
=> feat(ast convertors): wrap object key in quotes when starting with a number

.changeset/fast-forks-clap.md, packages/swc-plugin/src/shared/structures/state_manager.rs, packages/swc-plugin/tests/__swc_snapshots__/tests/stylex_transform_define_vars_test/stylex_transform_define_vars.rs/transforms_variables_object_with_nested_defined_vars_call.js, packages/swc-plugin/tests/__swc_snapshots__/tests/stylex_transform_define_vars_test/stylex_transform_define_vars.rs/transforms_variables_object_with_nested_defined_vars_calls.js, packages/swc-plugin/tests/stylex_transform_define_vars_test/stylex_transform_define_vars.rs
Fixing #16 
This PR allows to use the result of calling the function defineWars as parameters of a similar function in the same file
=> feat(define_vars): allow nested calls

crates/stylex-shared/src/shared/utils/js/evaluate.rs, crates/stylex-shared/tests/__swc_snapshots__/tests/stylex_validation_create_test/stylex_validation_create_dynamic_test.rs/dynamic_style_function_with_conditional_expression_fallback.js, crates/stylex-shared/tests/__swc_snapshots__/tests/stylex_validation_create_test/stylex_validation_create_dynamic_test.rs/dynamic_style_function_with_ternary_conditional_expression.js, crates/stylex-shared/tests/stylex_validation_create_test/stylex_validation_create_dynamic_test.rs
This PR adds the correct transformation of arrow function body with conditional expressions.
See issue https://github.com/Dwlad90/stylex-swc-plugin/issues/49 for more details
=> fix(dynamic styles): correct evaluate arrow function body

crates/stylex-shared/src/shared/utils/core/stylex_merge.rs, crates/stylex-shared/tests/__swc_snapshots__/tests/stylex_transform_stylex_props_test/stylex_props_call.rs/stylex_call_with_spread_operator.js, crates/stylex-shared/tests/__swc_snapshots__/tests/stylex_transform_stylex_props_test/stylex_props_call.rs/stylex_call_with_spread_operator_of_variable.js, crates/stylex-shared/tests/stylex_transform_stylex_props_test/stylex_props_call.rs
This PR allows passing a spread expression as arguments to a `stylex.props` call.
See issue https://github.com/Dwlad90/stylex-swc-plugin/issues/54 for more details
=> feat(style.props): allow to pass spread expressions

crates/stylex-rs-compiler/src/lib.rs
PR adds panic processing and the ability to continue working after the error has been resolved
=> fix(@stylexswc/rs-compiler): don't exit with exit code 1 when panic signal occurs

Cargo.lock, crates/stylex-shared/src/shared/constants/common.rs, crates/stylex-shared/src/shared/regex.rs, crates/stylex-shared/src/shared/utils/css/common.rs, crates/stylex-shared/src/shared/utils/css/tests/css_custom_properties_validation_test.rs
SWC css parser does not handle color functions correctly, such as `oklch`
=> fix(radial-gradient): exclude from normalizing

crates/stylex-shared/src/shared/constants/common.rs, crates/stylex-shared/src/shared/utils/css/common.rs, crates/stylex-shared/src/shared/utils/css/normalizers/tests/base.rs, crates/stylex-shared/src/shared/utils/css/tests/css_custom_properties_validation_test.rs
This PR temporarily excludes color channels such as `l | c | h` from normalization
=> fix(css functions): exclude color relative values from normalizing

crates/stylex-path-resolver/src/resolvers/mod.rs, crates/stylex-path-resolver/src/resolvers/tests.rs, crates/stylex-shared/src/shared/structures/state_manager.rs
This PR fixes an #179  with resolving theme style import paths when using `bun`'s monorepo.
=> fix(@stylexswc/path-resolver): exclude empty path from resolution

apps/nextjs-postcss-example/package.json, pnpm-lock.yaml
There is a difference between the npm documentation for the postcss-plugin between npm and the example code.
I believe that the postcss-plugin should actually be in devDependencies in this file, based on the documentation for the npm package, for example:
```json
"devDependencies": {
"autoprefixer": "^10.4.20",
"@stylexswc/postcss-plugin": "0.6.1-rc.2",
"@stylexjs/eslint-plugin": "^0.9.3",
"@types/node": "^22.5.1",
"@types/react": "^19.0.1",
"@types/react-dom": "^19.0.2",
"@typescript-eslint/parser": "^6.14.0",
"eslint": "^8.57.0",
"eslint-config-next": "15.0.4",
"rimraf": "^5.0.5",
"typescript": "^5.5.4"
}
```
Move @stylexswc/postcss-plugin to devDependencies
See https://github.com/Dwlad90/stylex-swc-plugin/issues/186
=> move @stylexswc/postcss-plugin to devDependencies

packages/nextjs-plugin/src/index.ts
As described in https://github.com/Dwlad90/stylex-swc-plugin/pull/189#issuecomment-2588086598 - we believe it is cleaner to only log the webpack environment information when a debug flag is defined.
only log webpack details in debug mode
=> fix(@stylexwc/nextjs-plugin): only log webpack details in debug mode

crates/stylex-path-resolver/src/package_json/mod.rs
This PR add more detailed error when parsing `package.json` failed
(Optional) Fixes #193
=> chore(get_package_json): generate more detailed error when package.json parsing failed

packages/postcss-plugin/src/builder.ts
pnpm installs dependencies locally for each package. npm (and also bun) install at the root of a monorepo.
The postcss-plugin example considers both of these install locations, however, the postcss-plugin builder code uses a `path.join` then it encounters an import path that does not match the current package path resulting in a path that is not accurate.
e.g.
```
cwd: /dwlad/stylex-swc-plugin/apps/nextjs-postcss-example/
filename: /dwlad/stylex-swc-plugin/node_modules/@stylexjs/open-props/lib/animationNames.stylex.js
```
The combination above (where `@stylexjs/open-props` has been installed at root) will result in: …
=> fix(@stylexswc/postcss-plugin): provide resolved pathname to postcss plugin builder

crates/stylex-rs-compiler/src/lib.rs, crates/stylex-rs-compiler/src/structs/mod.rs, crates/stylex-shared/src/shared/structures/state_manager.rs, crates/stylex-shared/src/shared/structures/stylex_options.rs, crates/stylex-shared/src/shared/structures/stylex_state_options.rs, crates/stylex-shared/src/shared/structures/tests/get_canonical_file_path_test.rs, packages/jest/src/index.ts, packages/postcss-plugin/src/bundler.ts, packages/postcss-plugin/src/index.ts, packages/rollup-plugin/src/index.ts, packages/unplugin/src/index.ts, packages/unplugin/src/utils/normalizeOptions.ts, packages/webpack-plugin/src/utils.ts
This function is used to normalize the options passed to the transform function of `@stylexswc/rs-compiler` crate. This is useful for ensuring that the options are in a consistent format before being passed to the compiler.
=> feat(stylex_compiler_rs): add `normalize_rs_options` util

crates/stylex-path-resolver/src/resolvers/mod.rs, crates/stylex-path-resolver/src/resolvers/tests.rs
This PR fix resolving StyleX calls from nested dependencies by `stylex_compiler_rs` crate
(Optional) Issue #215
=> fix(stylex_compiler_rs): resolving StyleX calls from dependencies

crates/stylex-path-resolver/src/resolvers/tests.rs
=> test(stylex_path_resolver): add local workspace node_modules to monorepo fixtures

.github/workflows/npm.yml, crates/stylex-shared/src/shared/regex.rs, crates/stylex-shared/src/shared/utils/css/normalizers/whitespace_normalizer.rs, crates/stylex-shared/src/shared/utils/css/tests/css_custom_properties_validation_test.rs
This PR includes changes to improve the handling of whitespace in CSS math expressions and adds new tests for CSS property transformations.
(Optional) Issue #232 
=> fix(whitespace_normalizer): parsing expressions with negative values

packages/nextjs-plugin/README.md, packages/nextjs-plugin/src/index.ts, packages/webpack-plugin/README.md, packages/webpack-plugin/src/index.ts, packages/webpack-plugin/src/types.ts
This pull request includes several updates to enhance the CSS transformation functionality in both the Next.js and Webpack plugins. The primary changes involve modifying the `transformCss` function to accept an additional `filePath` parameter, which allows for better handling of source maps and file annotations.
(Optional) Fixes #236 
=> fix(nextjs-plugin): pass the path to resource file to the postcss process to prevent warning

crates/stylex-shared/src/shared/utils/js/evaluate.rs, crates/stylex-shared/tests/__swc_snapshots__/tests/stylex_transform_stylex_props_test/naming_conventions_with_dynamisms.rs/stylex_call_props_with_renaming_dynamic_styles_prop_and_conflict_import_name.js, crates/stylex-shared/tests/stylex_transform_stylex_props_test/naming_conventions_with_dynamisms.rs
This pull request includes changes to improve error handling and add a new test case in the `stylex-shared` crate. The most important changes include enhancing the evaluation function to handle theme references and adding a test for dynamic style properties with conflicting import names.
Issue #240
=> fix(stylex_shared): prevent variable name conflicts with imported theme variable

crates/stylex-shared/src/shared/constants/messages.rs, crates/stylex-shared/src/shared/utils/js/evaluate.rs
This pull request introduces a new error message for theme import keys and integrates it into the existing codebase. The changes ensure that theme import keys are not used as object keys and provide appropriate error handling and messaging.
=> refactor(stylex_shared): improve error message when theme used as object property

.github/workflows/pr-validation.yml, crates/stylex-path-resolver/src/resolvers/mod.rs, crates/stylex-path-resolver/src/resolvers/tests.rs
This pull request includes several changes to the `stylex-path-resolver` module, focusing on improving the path resolution logic and adding new test cases. The most important changes include modifying the `resolve_file_path` function to handle extensions correctly, adding new test cases for workspace alias resolution, and updating existing test modules.
(Optional) Issue #258
=> fix(resolve_file_path): allow resolution of aliases that don't includes root path

crates/stylex-rs-compiler/README.md
This pull request includes updates to the `crates/stylex-rs-compiler/README.md` file to add a new section on enabling debug logging for the StyleX compiler. The most important changes include the addition of log levels, usage instructions for setting the `STYLEX_DEBUG` environment variable, and examples for different operating systems.
Documentation updates:
* Added a new "Debug" section explaining how to enable debug logging for the StyleX compiler using the `STYLEX_DEBUG` environment variable.
* Listed available log levels: `error`, `warn`, `info`, `debug`, and `trace`, with descriptions for each.
* Provided usage instructions for setting the `STYLEX_DEBUG` environment variable before running build commands.
* Included examples for setting the `STYLEX_DEBUG` variable in Bash, Windows …
=> docs(stylexswc/rs-compiler): add `debug` section

.github/release.yml
This pull request includes changes to the `.github/release.yml` file to add new labels for dependency updates.
* Added new labels for development dependencies: `dev-deps`, `dev-dependencies`, and `dev-depedency`.
=> ci(release): add dev-deps label

Cargo.toml
This pull request includes a small change to the `Cargo.toml` file. The change removes the dependency on `stylex_path_resolver` by deleting the line specifying its path.
Dependency removal:
* [`Cargo.toml`](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L54): Removed the dependency on `stylex_path_resolver` by deleting its path specification.
=> chore(cargo.toml): remove unnecessary stylex_path_resolver from workspace.dependencies

.github/workflows/cleanup-pr.yaml, .github/workflows/conventional-label.yaml, .github/workflows/pr-validation.yml
GitHub workflows can be triggered through various repository events, including incoming pull requests (PRs) or comments on Issues/PRs. A potentially dangerous misuse of the triggers such as pull_request_target or issue_comment followed by an explicit checkout of untrusted code (Pull Request HEAD) may lead to repository compromise if untrusted code gets executed in a privileged job.
This pull request updates GitHub Actions workflows to replace the use of the `pull_request_target` event with the `pull_request` event for improved security and consistency. The most important changes are outlined below.
* [`.github/workflows/cleanup-pr.yaml`](diffhunk://#diff-1f5c754b0cf9ef2da78aef14fdb8d04264ebe35e725f068a0554b00c8f91ea95L6-L8): Removed the `pull_request_target` event and retained only the …
=> ci(ga): use pull_request instead of pull_request_target

.github/workflows/release.yml
Potential fix for [https://github.com/Dwlad90/stylex-swc-plugin/security/code-scanning/31](https://github.com/Dwlad90/stylex-swc-plugin/security/code-scanning/31)
To fix the issue, we will add a `permissions` block to the `merge-master` job to explicitly define the least privileges required. Since the job involves merging branches and pushing changes, it requires `contents: write` permissions. We will also add a `permissions` block at the workflow level with `contents: read` as the default, ensuring other jobs inherit minimal permissions unless explicitly overridden.
---
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
=> Potential fix for code scanning alert no. 31: Workflow does not contain permissions

.github/workflows/cleanup-branch.yaml, .github/workflows/cleanup-pr.yaml, .github/workflows/cleanup.yaml, .github/workflows/fast-forward.yml, .github/workflows/pr-validation.yml, .github/workflows/self-approve.yml, apps/esbuild-unplugin-example/playwright.config.ts, apps/farm-unplugin-example/playwright.config.ts, apps/nextjs-example/playwright.config.ts, apps/nextjs-postcss-example/playwright.config.ts, apps/rollup-unplugin-example/playwright.config.ts, apps/rsbuild-unplugin-example/playwright.config.ts, apps/rspack-unplugin-example/playwright.config.ts, apps/solid-unplugin-example/playwright.config.ts, apps/vite-unplugin-example/playwright.config.ts, apps/vue-unplugin-example/playwright.config.ts, apps/webpack-unplugin-example/playwright.config.ts
Potential fix for [https://github.com/Dwlad90/stylex-swc-plugin/security/code-scanning/19](https://github.com/Dwlad90/stylex-swc-plugin/security/code-scanning/19)
Potential fix for [https://github.com/Dwlad90/stylex-swc-plugin/security/code-scanning/20](https://github.com/Dwlad90/stylex-swc-plugin/security/code-scanning/20)
Potential fix for [https://github.com/Dwlad90/stylex-swc-plugin/security/code-scanning/21](https://github.com/Dwlad90/stylex-swc-plugin/security/code-scanning/21)
Potential fix for [https://github.com/Dwlad90/stylex-swc-plugin/security/code-scanning/22](https://github.com/Dwlad90/stylex-swc-plugin/security/code-scanning/22)
Potential fix for [https://github.com/Dwlad90/stylex-swc-plugin/security/code-scanning/23](https://github.com/Dwlad90/stylex-swc-plugin/security/cod …
=> Potential fix for code scanning alert no. 23: Workflow does not contain permissions

crates/stylex-path-resolver/.lintstagedrc.js, crates/stylex-path-resolver/fixtures/exports/node_modules/stylex-lib-dist-exports-commonjs-esm/package.json, crates/stylex-path-resolver/fixtures/exports/package.json, crates/stylex-path-resolver/src/enums/mod.rs, crates/stylex-path-resolver/src/lib.rs, crates/stylex-path-resolver/src/package_json/mod.rs, crates/stylex-path-resolver/src/resolvers/mod.rs, crates/stylex-path-resolver/src/resolvers/tests.rs, crates/stylex-path-resolver/src/utils/mod.rs
This pull request introduces support for handling both CommonJS and ESM exports in the `stylex-path-resolver` crate, along with improvements to sorting logic and additional test coverage. Key changes include the introduction of a new `ExportsType` enum, updates to the `PackageJsonExtended` structure, modifications to export resolution logic, and the addition of new test cases.
* Added a new `ExportsType` enum in `crates/stylex-path-resolver/src/enums/mod.rs` to differentiate between simple and complex export structures. (`[crates/stylex-path-resolver/src/enums/mod.rsR1-R9](diffhunk://#diff-6049ce0d074fefb2bcbbf161f19606288a7d7a003ecac4a454d56559eda76f1bR1-R9)`)
* Updated the `exports` field in the `PackageJsonExtended` struct to use the new `ExportsType` enum, allowing for more flexible …
=> feat(stylex_path_resolver): resolve path of esm modules

crates/stylex-shared/src/shared/transformers/tests/stylex_create_test.rs, crates/stylex-shared/src/shared/utils/core/add_source_map_data.rs, crates/stylex-shared/src/shared/utils/log/build_code_frame_error.rs, crates/stylex-shared/src/transform/fold/fold_jsx_attr_or_spread.rs
This pull request introduces several improvements and fixes to the StyleX shared utilities, primarily focusing on more robust handling of source maps, error logging, and expression parsing. The most significant changes include enhanced diagnostics for Next.js mismatches, consistent usage of the `COMPILED_KEY` constant, and improved logic for locating expression spans in source code. Additionally, new logic was added to better handle string concatenation expressions when generating code frames.
* Added a warning message for users of Next.js when a source map span cannot be found, explaining potential server/client AST mismatches and how to debug them (`add_source_map_data.rs`).
* Improved debug and warning log formatting in both `add_source_map_data.rs` and `build_code_frame_error.rs` for …
=> fix(add_source_map_data): fix with using template string
